language: python
python:
  - "2.7.13"
  - "3.5.3"
  - "3.6.2"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_for_test.txt

# command to run tests
script: python -m unittest discover tests
