language: python
python:
  - "3.6.2"
  - "3.7.2"
  - "3.8.2"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_for_test.txt
  - pip install -e .

# command to run tests
script:
  - python -m pytest --doctest-modules

